version: '3.4'

services:
  officecontrolsystem:
    image: ${DOCKER_REGISTRY-}officecontrolsystem
    container_name: officecontrolsystem
    build:
      context: .
      dockerfile: OfficeControlSystem/Dockerfile
    ports:
      - "5000:5000"
      - "5001:5001"

  officecontrolsystem.database:
    image: postgres:latest
    container_name: officecontrolsystem.database
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: officecontrolsystem
    volumes:
      - ./.containers/officecontrolsystem-db:/var/lib/postgresql/data
    ports:
      - 5432:5432
